### ISSUE TITLE
Unable to initialize behat Test environment when running docker within another docker image(pod)

### ISSUE THREAD

**Issue by pdubey2019** [moodlehq/moodle-docker#124]
getting this error while initializing test environment : 
`-Installing instaclick/php-webdriver (dev-local 3df8272): Cloning 3df827208e
 (service: behat-test) (step: test) Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
 (service: behat-test) (step: test) Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+e747484478598+2020-05-06+1629

 to retrieve a token. It will be stored in "/var/www/.composer/auth.json" for future use by Composer.`

Test step where I got this error: -
php admin/tool/behat/cli/init.php -j=1

Not sure how to resolve this. Please can someone look in to this

**Comment by stronk7** [comment]
Hi @pdubey2019 ,

yes, that's a known issue, happening because the php images are git-less (we are considering when we should add git and other tools to them).

Until then, there are a few workarounds to be able to get that working:

1) Perform the `php composer.phar install` in the host. Assuming you've `git` or `.composer/auth.json` in the host. That way the mounted moodle will already contain the vendor directory with all the stuff installed.

2) Within the container, use `apt update && apt install git`, so git will be available there. And will be used when the ssh/git connection is not allowed.

3) If you've it, use `docker cp` and copy the `.composer/auth.json` token to `/var/www/.composer/`

Hope it helps!

PS: I also hope we can get rid of that custom `instaclick/php-webdriver` we are forced to use (and causes the problem). Ideally that will be possible when they release the needed changes upstream (although I'm not super-confident).

**Comment by stronk7** [comment]
Just FYI, the `moodlehq/moodle-php-apache` images are being rebuilt right now in order to include in all them `git`. That should help to the composer install within the containers because it will be used as fallback for those`instaclick` custom repo installations.

So I'm going to close this because tests are looking good and have been able to install composer without problems with the new images.

If the problem persists, let us know.

Ciao :-)

**Comment by pdubey2019** [comment]
Hi

This is not related to above issue though but just to expedite process or
might be one look can help me to resolve this issue

I am getting below error when running behat against latest Moodle 39 master
branch so please can you help me to suppress or ignore these warning when
running behats. We got a ticket to resolve these warnings in future but
till then if I can resolve this for time being

debugging() message/s found:
      The setting plagiarism:turnitinsim_use is deprecated. Use
plagiarism_turnitinsim:enabled instead
      line 204 of /lib/plagiarismlib.php: call to debugging()
      line 121 of /lib/plagiarismlib.php: call to
plagiarism_load_available_plugins()
      line 192 of /mod/assign/mod_form.php: call to
plagiarism_get_form_elements_module()
      line 214 of /lib/formslib.php: call to
mod_assign_mod_form->definition()
      line 130 of /course/moodleform_mod.php: call to
moodleform->__construct()
      line 141 of /course/modedit.php: call to moodleform_mod->__construct()

Any help is highly appreciated.

Thanks
Prateek
