### ISSUE TITLE
Getting Error when running behats "debugging() message/s found:" against Moodle 39 master branch

### ISSUE THREAD

**Issue by pdubey2019** [moodlehq/moodle-docker#128]
Hi
I am trying to run behats for testing plugin but now I am getting below errors. please can someone tell a way to supress or ignore  these errors when running behats :-

`debugging() message/s found:
      The setting plagiarism:turnitinsim_use is deprecated. Use plagiarism_turnitinsim:enabled instead
      line 204 of /lib/plagiarismlib.php: call to debugging()
      line 121 of /lib/plagiarismlib.php: call to plagiarism_load_available_plugins()
      line 192 of /mod/assign/mod_form.php: call to plagiarism_get_form_elements_module()
      line 214 of /lib/formslib.php: call to mod_assign_mod_form->definition()
      line 130 of /course/moodleform_mod.php: call to moodleform->__construct()
      line 141 of /course/modedit.php: call to moodleform_mod->__construct()`

**Comment by scara** [comment]
Hi @pdubey2019,
you "can't" suppress them since Moodle Docker Toolbox is used to develop/test Moodle related code and that is the reason why any deprecated API should warn you.
You're using something - 3rd party plug-in like a theme or a course format? - not ready for Moodle 3.9 release.

More at [MDL-67872](https://tracker.moodle.org/browse/MDL-67872).

HTH,
Matteo
