### ISSUE TITLE
Changing php version later on

### ISSUE THREAD

**Issue by t-schroeder** [moodlehq/moodle-docker#137]
I wanted to try doing an upgrade from Moodle 3.1 to 3.9 to test some upgrade problem in a third-party plugin. So I setup container with Moodle 3.1 and PHP 5.6 but for the upgrade to Moodle 3.9 I need a newer PHP version. Is it possible to switch the PHP version in an already existing container?

**Comment by scara** [comment]
Hi @t-schroeder,
this is the tracker for the issues of the code hosted in this repo: you should ask for help in the Moodle Community e.g. https://moodle.org/mod/forum/view.php?id=28.

That being said:

> Is it possible to switch the PHP version in an already existing container?

AFAIK no, at least in a simple way:
1. [easy] you should create a commit of your running container
1. [easy] tag that commit to best fit with your image registry
1. run the new image: there you should remove the current PHP version and install the new one; than, again, a new commit&tag to preserve the bumping in a new image
1. [easy] finally, run a new container from the image above, after the PHP version bump

But you can use `MOODLE_DOCKER_PHP_VERSION` with the Moodle Docker Toolbox, the code hosted in this repo, to run a specific PHP version among those supported as listed [here](https://github.com/moodlehq/moodle-docker/blob/43f2b9035d3d608a9cb045b52402320056c66b11/README.md#environment-variables) i.e. `7.4`, `7.3`, `7.2`, `7.1`, `7.0`, `5.6` (default: `7.2`).

Give the README of this repo a read: this tool will IMHO be of great help in your case.

HTH,
Matteo

**Comment by stronk7** [comment]
Yeah, although for sure you will need a 2-steps upgrade, because Moodle 3.1 and 3.9 do not share any PHP version supported:.

- Step1: Moodle 3.1 works with PHP 7.0, so surely that's the initial `MOODLE_DOCKER_PHP_VERSION` that you should be using. With that PHP version you can upgrade up to Moodle 3.6.
- Step2: Then, Moodle 3.6 (latest) works with PHP 7.3 and that's the version that you should be using to upgrade to Moodle 3.9.

Note I'm not sure about which is the nature of the site that you want to try upgrades on, if it's a real one, I'm not sure that you can use moodle-docker for that, because the intermediate status between the 2 steps can become lost (unless you're able to add one more container on-the-fly (I'm sorry I never have tried that, maybe that's what @scara is explaining above, heh).

For sure you can test the 2 steps above separately. Try step1 and, if everything is ok at the end, then try step2.

Ciao :-)

PS: I'm closing this as far as it's not an issue.

**Comment by t-schroeder** [comment]
Thanks for the info. It was just a theoretical case I would like to test. @stronk7 the thing is I wanted to test specifically an upgrade from 3.1 to 3.9 in a single step. This should be possible in theory right? You would just need to replace the 3.1 code with the 3.9 code and switch to the newer PHP version before performing the upgrade.

Thanks for the info. I will try some of this when I have time.

**Comment by stronk7** [comment]
> This should be possible in theory right? You would just need to replace the 3.1 code with the 3.9 code and switch to the newer PHP version before performing the upgrade

No, that's not possible. [Moodle 3.9 requires Moodle 3.5](https://github.com/moodle/moodle/blob/master/admin/environment.xml#L2985) to upgrade. It was decided, following the requirements policies @ [MDL-65809](https://tracker.moodle.org/browse/MDL-65809).

And, be warned, to "tweak" that `environment.xml` file is not enough (in case you're thinking about that). Because, as part of the issue... we remove all the upgrade steps previous to Moodle 3.5, so it won't be running the correct (complete) upgrade steps.

Ciao :-)

**Comment by t-schroeder** [comment]
That's very valuable insight. Thanks a lot. That solves the theoretical upgrade problem I was worrying about. :)
