### ISSUE TITLE
Reconsider branching strategy for versions

### ISSUE THREAD

**Issue by danpoltawski** [moodlehq/moodle-docker#15]
I am not sure if using branches of this project is the best way to manage php versions, it might be better to control it with an environment variable a bit like i have done with the browser. Needs some consideration.

**Comment by abias** [comment]
I would definitely appreciate if php versions could be controlled with an environment variable and not with a branch.

I see at least to benefits:
* The maintainance effort is lowered because you don't have to merge every commit to all branches.
* As a user, it's enough to have one copy of this repo on my disk. Currently, to use multiple PHP versions, I have to have multiple checked out copied of this repo at hand.

On the other hand, I don't see a real downside compared to the branching approach.

So I compared the php70 branch and the php56 branch with the master/php71 branch.

The main difference which I spotted was:

```
/base.yml
<     image: moodlehq/moodle-php-apache:7.1
---
>     image: moodlehq/moodle-php-apache:5.6
```

This should be convertible into an environment variable easily.

I also spotted this difference in /tests/test.sh:
```
<     testcmd="bin/moodle-docker-compose exec -T webserver php admin/tool/behat/cli/run.php --tags=@auth_manual"
---
>     testcmd="bin/moodle-docker-compose exec -T webserver php admin/tool/behat/cli/run.php --tags=@core_tag"
```
but I don't know if this difference is by purpose or some legacy. 

Additionally, I saw this difference in the php56 branch in /db.mssql.yml:
```
<       MOODLE_DOCKER_DBTYPE: sqlsrv
---
>       MOODLE_DOCKER_DBTYPE: mssql

```
Again, I don't know if this difference is by purpose or some legacy.

**Comment by abias** [comment]
In the meantime, I have seen that https://github.com/moodlehq/moodle-php-apache also has branches and that there, the master and the php70 branch only differs in terms of the installed php versions, but that the master and the php56 differs in several aspects.

**Comment by danpoltawski** [comment]
> I also spotted this difference in /tests/test.sh:

This is a bug (I didn't apply a revert to the branch). I've fixed that difference now.

> Additionally, I saw this difference in the php56 branch in /db.mssql.yml

This is required, the drivers used are different.

**Comment by danpoltawski** [comment]
New `MOODLE_DOCKER_PHP_VERSION` has been introduced and the branches have now been removed.

**Comment by abias** [comment]
This change is working like a charm - thank you, Dan!
