### ISSUE TITLE
Behat Tests sending mails

### ISSUE THREAD

**Issue by georgmaisser** [moodlehq/moodle-docker#197]
I am trying to include automatically sent mails in our behat tests.

I have 
- set smtphosts to mailhog:1025 for the behat site
- in behat/classes/util.php I've set „noemailever“ to 0
- In the same file, I've set $DB->set_field('message_processors', 'enabled', '1', array('name' => 'email'));
- After triggering the e-mail in our plugin in the .feature file, I've added "I run all adhoc tasks"

Still, no mails in mailhog. Any ideas what more I need to do? Thank you!

**Comment by aspark21** [comment]
Hi George,

Not really the right place to ask about this but you can ask in the forums - https://moodle.org/course/view.php?id=5#section-3 - or in Dev chat - https://docs.moodle.org/dev/Chat

**Comment by georgmaisser** [comment]
> Hi George,
> 
> Not really the right place to ask about this but you can ask in the forums - https://moodle.org/course/view.php?id=5#section-3 - or in Dev chat - https://docs.moodle.org/dev/Chat

Hi, thanks for the reply, but I guess it has something to do with the Moodle-docker setup and the used configuration, so I don't think it would be a question to ask on Moodle.org.

The inclusion of mailhog in this Moodle-docker project is a cool feature and I am asking how to also use it for the behat tests.

**Comment by scara** [comment]
HI @georgmaisser,
> Any ideas what more I need to do? Thank you!

Never try by myself: it looks like you're almost there but `cron`: the Moodle Docker Toolbox does not run any Moodle cron and I'm not sure your message to be sent by an _adhoc_ task.
Did you extend `\core\task\adhoc_task` in your plug-in?
Otherwise, try to hit the [web cron](https://github.com/moodle/moodle/blob/0c63990e4faf67ad9759a97a42840f4502c73795/lib/behat/classes/util.php#L109-L120).

BTW, maybe https://moodle.org/mod/forum/discuss.php?d=354012#p1428125 could be of help for a different approach.

HTH,
Matteo

**Comment by andrewnicols** [comment]
Hi @georgmaisser ,

This is not an issue with the `moodle-docker` repository. When running Behat, you must allow configuration for any non-default settings. You need to explicitly allow any setting in the `$CFG->behat_extraallowedsettings` array as documented in `config-dist.php`.

I'll warn you that this isn't something we currently recommend - you will also need to write steps to confirm that mails arrived in MailHog (which is likely non-trivial).
