### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by akshat-khare** [moodlehq/moodle-docker#268]
I followed the quick start and access localhost:8000 but it says Forbidden
Forbidden
You don't have permission to access this resource.

Apache/2.4.56 (Debian) Server at localhost Port 8000
What am I doing wrong?

**Comment by scara** [comment]
Hi @akshat-khare,
could you share with us more about your environment and the exact sequence of commands executed there?
My guess is that there is no Moodle code available in the path set into `MOODLE_DOCKER_WWWROOT`.

HTH,
Matteo

**Comment by akshat-khare** [comment]
Yeah. Where do I need to place moodle code? Its not there in Readme. Can you please explain the steps here? Where is MOODLE_DOCKER_WWWROOT set?

**Comment by stronk7** [comment]
Hi @akshat-khare ,

I think that the information in the development docs can be helpful for you. More exactly, here you will find information about the 1st steps needed to get a nice Moodle development environment ready:

https://moodledev.io/docs/guides/git#installing-git-on-your-computer

I would recommend, also, to spend a few time understanding all the information in that page and in linked ones.

Once you've a local copy of the Moodle git repository, surely you can continue with the moodle-docker instructions (or any other alternative, like WAMP, MAMP, manual installation...).

Hope it helps. I'm going to close this now, because it's not a moodle-docker issue. 

Ciao :-)

**Comment by akshat-khare** [comment]
I understand what you are getting at but instructions for a docker compose kind of setup are pretty straight forward. I was able to up the moodle with bitnami docker compose but faced difficulty this way. As an open source ecosystem we should be pretty neat with README.md. But I respect your expertise on moodle and will go through the instructions you mentioned. But please take this into cognizance, just a humble request.

**Comment by scara** [comment]
Hi @akshat-khare,
this is a Toolbox for developing and testing i.e. it does not contain any Moodle core code neither plug-ins: the code should be already there in the file system your Docker Engine could access to and it is mapped into the Toolbox as written in the [_QuickStart_](https://github.com/moodlehq/moodle-docker/blob/master/README.md#quick-start) section:
> ```bash
> # Set up path to Moodle code
> export MOODLE_DOCKER_WWWROOT=/path/to/moodle/code
> ```

The Bitnami proposal takes the code into the image and it is supposed to be production ready while this Toolbox has other goals.
What are yours?

HTH,
Matteo
