### ISSUE TITLE
Document AMD build step

### ISSUE THREAD

**Issue by fulldecent** [moodlehq/moodle-docker#287]
When developing moodle plugins using client side JavaScript, it is necessary to build the JavaScript from amd using some build process. (Source: https://moodledev.io/docs/guides/javascript/modules)

This process requires some infrastructure (Node?) which I think is included in moodle-docker and is in-scope for this repo.

However the build process is not supported inside the docker image:

```sh
root@1be09377965d:/var/www/html# npx grunt amd
bash: npx: command not found
```

If module development is indeed supported in moodle-docker, we should add documentation for same into README.md. Or if it's missing let's please add it.

**Comment by paulholden** [comment]
Installation is documented at https://moodledev.io/general/development/tools/nodejs#grunt

**Comment by paulholden** [comment]
Hi @fulldecent - this repository is intended as a _testing_ environment for Moodle, rather than a _development_ environment

I've linked to the dev docs above for Node installation along with other dependencies

**Comment by fulldecent** [comment]
Thank you, I hear you.

If that's the case, this advertisement should be scaled back:

![Screenshot 2024-04-09 at 15 49 57](https://github.com/moodlehq/moodle-docker/assets/382183/8840880e-dbd7-40f2-b714-0547a75d3df6)

The the project scope can be reduced.

![Screenshot 2024-04-09 at 15 51 18](https://github.com/moodlehq/moodle-docker/assets/382183/ebaeee34-2aae-452e-8eb0-ed4da7782be1)

And then we can remove all references to this repo as a developer resource. And then also we should start a new project to make a moodle dev docker.

---

The reference you point to at https://moodledev.io/general/development/tools/nodejs#grunt assuems that `npx` is installed on the development environment. So probably this docker project, or a moodles-dev-docker successor should support that.

**Comment by stronk7** [comment]
Hola,

not sure which is the problem here, you can follow the instructions available in the page that @paulholden linked, **both in the host OR within the docker container** and you will get all the nodejs stack installed and running.

Personally I do that in the host, because the container is not needed for all that nodejs stuff, but the very same can be done within the container if you prefer to do so.

- Install nvm: `wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash`
- Install nodejs: `nvm install && nvm use`
- Use nodejs: `npx grunt amd`

Exactly the same instructions apply to both, so I don't get which one the problem is. As said, the above works exactly the same in the host or inside the container (but I think it's "silly" to run that inside the PHP container, that's just a very personal opinion, feel free, of course).

Ciao :-)

**Comment by paulholden** [comment]
Thanks again @fulldecent - however nothing in the language you reference specifies that this is intended to be a development environment

"[...] aimed at Moodle developers and testers to easily **deploy a testing environment**" (emphasis mine)

**Comment by fulldecent** [comment]
In my mind developers develop. But here developers do testing. Maybe this is an American English/Australian English thing, lol. 

Thanks for that note. With it this is actually a development environment. I'll add a note to README if it's in project scope.

**Comment by sharpchi** [comment]
The work-around I use is to run npm install on my host machine in the Moodle html dir. I then use "nvm use" to make sure the right version is in use, and run Grunt from the host.
